description: Welcome to Better Informatics. The student run website for students in the School of Informatics.

sass:
   sourcemap: true

url: "https://betterinformatics.com" # update previous line
domain: "betterinformatics.com" # update next line
baseurl: "" # does not include hostname

markdown: redcarpet

collections:
    sections:
    pages:
        output: true
        permalink: "/:path"

defaults:
    - scope:
        path: ""
        type: "sections"
      values:
        pinned: false # by default, not pinned
        semester: 100 # "Other" stuff is pushed to the end
        archived: false
        course-acronym: ""

    - scope:
        path: "" # an empty string here means all files in the project
        type: "pages"
      values:
        layout: "frontpage"
        show-archived: false
